name: Pull Request Integration Test

on:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn build

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run: yarn test
